/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#41493e',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#717a6d',
        'outline-variant': '#c0c9bb',
        'surface-tint': '#2a6b2c',
        primary: '#00450d',
        'on-primary': '#ffffff',
        'primary-container': '#1b5e20',
        'on-primary-container': '#90d689',
        'inverse-primary': '#91d78a',
        secondary: '#1b6d24',
        'on-secondary': '#ffffff',
        'secondary-container': '#a0f399',
        'on-secondary-container': '#217128',
        tertiary: '#00442d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#005e3f',
        'on-tertiary-container': '#4ddda2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#acf4a4',
        'primary-fixed-dim': '#91d78a',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#0c5216',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        // Status alerts (from DESIGN.md functional palette)
        success: '#16a34a',
        'success-bg': '#ecfdf5',
        warning: '#d97706',
        'warning-bg': '#fffbeb',
        danger: '#dc2626',
        'danger-bg': '#fef2f2',
        info: '#0284c7',
        'info-bg': '#f0f9ff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xxs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
